# Generated by Django 5.1.4 on 2025-07-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.TextField(default='this is a body'),
            preserve_default=False,
        ),
    ]
